<?php
$pos1 = strpos($_SERVER['REQUEST_URI'], "producto.php");
$pos2 = strpos($_SERVER['REQUEST_URI'], "categoria.php");
$pos3 = strpos($_SERVER['REQUEST_URI'], "carro.php");

?>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Detalle del producto</h4>
      </div>
      <div class="modal-body">
        <?php if($pos3 != false): ?>
        <iframe src='#' width="100%" height="600px" frameborder=0 style='padding:8px'></iframe>
      <?php elseif($pos1 != false || $pos2 !=false): ?>
        <div id='data-container'></div>
      <?php endif ?>
      </div>
    </div>
  </div>
</div>
